version: "2.2"
services:
  postgres:
     image: postgres
     environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: 123456
     ports:
       - '5433:5432'

  eventstore:
     build:
       context: .
     environment:
       DB_SCHEMA: postgres
       DB_USER: postgres
       DB_PASSWORD: 123456
       DB_HOST: postgres
     volumes:
        exportedFiles
          
     depends_on:
         - postgres